# Generated by Django 2.2.7 on 2020-06-14 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hesap_Bilgileri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iban', models.CharField(max_length=200)),
                ('hesap_adi', models.CharField(max_length=300)),
                ('banka_adi', models.TextField(max_length=400)),
                ('hesap_türü', models.CharField(max_length=200)),
                ('sira', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='İletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=300)),
                ('adres', models.TextField()),
                ('telefon', models.CharField(max_length=200)),
                ('gsm', models.CharField(max_length=200)),
                ('e_posta', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=400)),
                ('sira', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nedir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=300)),
                ('ozet', models.TextField()),
                ('metin', models.TextField()),
                ('sira', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=400)),
                ('logo', models.ImageField(upload_to='media')),
                ('sira', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Temalar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=300)),
                ('fiyat', models.FloatField()),
                ('iskonto', models.IntegerField()),
                ('sira', models.IntegerField()),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onnumara.Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Referanslar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=400)),
                ('logo', models.ImageField(upload_to='media')),
                ('sira', models.IntegerField()),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onnumara.Temalar')),
            ],
        ),
    ]
